### PR TITLE
diff: keep priority for "range" filter

### LINKED ISSUE #413: sync-diff-inspector shard mode Based on the field range query data comparison, the range sql splicing is incorrect
image
image
image
[check.log](https://github.com/pingcap/tidb-tools/files/6062441/check.log)

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close https://github.com/pingcap/tidb-tools/issues/413

### What is changed and how it works?
before this PR, if user specified `range = "id >= 4001 and id < 6001"` the WHERE clause may be `WHERE ((`id` < ?) OR (`id` = ? AND `name` <= ?) AND id >= 4001 and id < 6001)`, we could see that first `(`id` < ?)` will shortcut rest of WHERE

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to be included in the release note
   修复了 sync-diff-inspector 配置中`range`可能不生效的问题

### CODE REVIEW

**Comment by lance6716** [comment]
cc @WentaoJin

**Comment by wentaojin** [comment]
> cc @WentaoJin

@lance6716 tks fixed，test using the pr，running result is good ，but splicing sql that can be optimized to remove unnecessary and unnecessary conditions
image

**Review by 3pointer — COMMENTED** [review]
/lgtm

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
