### PR TITLE
Loader: do not retry for truncate error

### LINKED ISSUE #114: Loader: do not retry for truncate error
truncate error is not retriable.

Truncate error should be check as well as duplicate key error.

https://github.com/pingcap/tidb-tools/blob/master/loader/db.go#L72

### PR DESCRIPTION
**Pull request by holys**
this should fixed #114 

@zhangjinpeng1987  @shenli  @GregoryIan  PTAL

### CODE REVIEW

**Comment by GregoryIan** [comment]
LGTM

**Comment by holys** [comment]
@andelf  PTAL

**Comment by holys** [comment]
@nolouch  PTAL

**Comment by nolouch** [comment]
LGTM

**Pull request merged**
