### PR TITLE
解决分库分表时,延迟关闭rows导致循环多次堵塞的问题

### PR DESCRIPTION
**Pull request by regend**
### What problem does this PR solve? 
当配置分库分表时,每当t.SourceTables有多个,for循环里执行到第二次及以上时,会卡在rows, err := db.QueryContext(ctx, query, args...)这里没有执行下去.

### What is changed and how it works?
取消延迟关闭rows,改为每次拿到结果就关闭

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
thanks, could you please fix the unit test

**Comment by lance6716** [comment]
Hi, we meet this error in #411, and want to fix it by https://github.com/pingcap/tidb-tools/pull/412

Could you fix the unit test, so we could merge your PR instead of #412

**Comment by lance6716** [comment]
replaced by #412

**Pull request closed without merging**
