### PR TITLE
sync_diff_inspector: fix the snapshot using the DateTime string

### PR DESCRIPTION
**Pull request by SE-Bin**
### What problem does this PR solve? 
Tiny fix for the Snapshot using the DateTime string like "2020-01-01 20:20:20"
image

### What is changed and how it works?
Enclose **tidb_snapshot** in Double quotes `""` for adding it in the dbDSN

### Check List 

Tests 

 - Manual test 

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
LGTM, and it is better to modify the integration test https://github.com/pingcap/tidb-tools/blob/master/tests/sync_diff_inspector/snapshot/run.sh#L12, we can do it later

**Comment by WangXiangUSTC** [comment]
@GMHDBJD PTAL

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]

**Pull request merged**
