### PR TITLE
*: update tidb

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve? 
`ticdc` needs to update tidb to a newer version and `ticdc` also imports `tidb-tools`, so we have to update `tidb-tools` first.

### What is changed and how it works?
- update tidb
- replace `pingcap/parser` with `pingcap/tidb/parser`

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by disksing** [comment]
The CI failure could be caused by a bug of TiDB.

**Comment by Ehco1996** [comment]
> The CI failure could be caused by a bug of TiDB.

😅
have we found the root casue or is there a tracking issue ?

**Comment by lance6716** [comment]
replaced by #532

**Pull request closed without merging**
