### PR TITLE
check: some privilege should be global-level

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
part of https://github.com/pingcap/dm/issues/1320

### What is changed and how it works?
update parser to parse and check that RELOAD, REPLICATION CLIENT, REPLICATION SLAVE should be global-level.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @GMHDBJD @csuzhangxc

**Comment by lance6716** [comment]
some new syntax of MySQL 8.0 is not supported, for example, grant role like

```
GRANT `r1`@`%`,`r2`@`%` TO `u1`@`localhost`
```

on the other hand, our old way of checking has better compatibility about new syntax. So I prefer this PR should not merge until (at least) it can pass MySQL 8.0's syntax.

https://dev.mysql.com/doc/refman/8.0/en/grant.html

**Comment by lance6716** [comment]
https://dev.mysql.com/doc/refman/8.0/en/partial-revokes.html

Should tell user if MySQL has enabled `partial_revokes`, please skip this check and check privileges manually

**Comment by lance6716** [comment]
now blocked by parser didn't recognize [Dynamic Privileges](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#privileges-provided-dynamic). need https://github.com/pingcap/parser/issues/1143

**Comment by lance6716** [comment]
PTAL @GMHDBJD @lichunzhu @leoppro

**Comment by GMHDBJD** [comment]
What‘s the other part of [pingcap/dm#1320](https://github.com/pingcap/dm/issues/1320) 😂

**Comment by lance6716** [comment]
> What‘s the other part of [pingcap/dm#1320](https://github.com/pingcap/dm/issues/1320) 😂

I think the other part (also the last part) is update dependency 😂

**Comment by lance6716** [comment]
> What‘s the other part of [pingcap/dm#1320](https://github.com/pingcap/dm/issues/1320) 😂

I think the other part (also the last part) is updating dependency of DM😂

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
