### PR TITLE
sync_diff_inspector: enable expression-index by default

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Allow sync_diff_inspector to compare table with expression index

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
seems there're errors related to schema comparing of DM optimisic sharing DDL🤔

not sure what's changed

```
"c2":schemacmp.Tuple{schemacmp.maybe{Lattice:schemacmp.singleton{value:""}}, schemacmp.singleton{value:""}, schemacmp.singleton{value:false}, schemacmp.typ{Tuple:schemacmp.Tuple{schemacmp.fieldTp{value:0xfe}, 50, 0, schemacmp.singleton{value:0x80}, false, 0xff, schemacmp.maybe{Lattice:schemacmp.singleton{value:0x0}}, schemacmp.singleton{value:"binary"}, schemacmp.singleton{value:"binary"}, schemacmp.StringList(nil)}}}
"c2":schemacmp.Tuple{schemacmp.maybe{Lattice:schemacmp.singleton{value:"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}}, schemacmp.singleton{value:""}, schemacmp.singleton{value:false}, schemacmp.typ{Tuple:schemacmp.Tuple{schemacmp.fieldTp{value:0xfe}, 50, 0, schemacmp.singleton{value:0x80}, false, 0xff, schemacmp.maybe{Lattice:schemacmp.singleton{value:0x0}}, schemacmp.singleton{value:"binary"}, schemacmp.singleton{value:"binary"}, schemacmp.StringList(nil)}}}, 
```

**Comment by lance6716** [comment]
another error

note: module requires Go 1.16

**Comment by lance6716** [comment]
> seems there're errors related to schema comparing of DM optimisic sharing DDL🤔
> 
> not sure what's changed
> 
> ```
> "c2":schemacmp.Tuple{schemacmp.maybe{Lattice:schemacmp.singleton{value:""}}, schemacmp.singleton{value:""}, schemacmp.singleton{value:false}, schemacmp.typ{Tuple:schemacmp.Tuple{schemacmp.fieldTp{value:0xfe}, 50, 0, schemacmp.singleton{value:0x80}, false, 0xff, schemacmp.maybe{Lattice:schemacmp.singleton{value:0x0}}, schemacmp.singleton{value:"binary"}, schemacmp.singleton{value:"binary"}, schemacmp.StringList(nil)}}}
> "c2":schemacmp.Tuple{schemacmp.maybe{Lattice:schemacmp.singleton{value:"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}}, schemacmp.singleton{value:""}, schemacmp.singleton{value:false}, schemacmp.typ{Tuple:schemacmp.Tuple{schemacmp.fieldTp{value:0xfe}, 50, 0, schemacmp.singleton{value:0x80}, false, 0xff, schemacmp.maybe{Lattice:schemacmp.singleton{value:0x0}}, schemacmp.singleton{value:"binary"}, schemacmp.singleton{value:"binary"}, schemacmp.StringList(nil)}}}, 
> ```

fixed by https://github.com/pingcap/tidb-tools/pull/532

**Comment by dveeden** [comment]
@glorv @lance6716 what's the plan with this PR?

**Pull request closed without merging**
