### PR TITLE
merge develop branch

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
1. add pump client
2. update binlogctl

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
don't merge now, can take a look first @july2993 @GregoryIan

**Comment by WangXiangUSTC** [comment]
@july2993  @GregoryIan  PTAL

**Comment by july2993** [comment]
LGTM

**Comment by IANTHEREAL** [comment]
LGTM

**Comment by IANTHEREAL** [comment]
where to download old version？

**Comment by WangXiangUSTC** [comment]
binlogctl and sync_diff_inspector is package in kafka version tidb-binlog @GregoryIan

**Pull request merged**
