### PR TITLE
Update grpc

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: ref #819 

### What is changed and how it works?

Specifying v1.63.2 as it is used by tikv client.

Otherwise this happens:
```
$ make build
GO111MODULE=on go version
go version go1.23.3 linux/amd64
gofmt (simplify)
#go get github.com/golang/lint/golint
vet
# github.com/tikv/client-go/v2/internal/client
../../../go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240424052342-0229f4077f0c/internal/client/client.go:337:37: undefined: experimental.WithRecvBufferPool
../../../go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240424052342-0229f4077f0c/internal/client/client.go:337:61: undefined: grpc.NewSharedBufferPool
make: *** [Makefile:86: check] Error 1
```

```
$ go get -u google.golang.org/grpc@v1.63.2
go: upgraded golang.org/x/crypto v0.22.0 => v0.29.0
go: upgraded golang.org/x/net v0.24.0 => v0.31.0
go: upgraded golang.org/x/sync v0.7.0 => v0.9.0
go: upgraded golang.org/x/sys v0.19.0 => v0.27.0
go: upgraded golang.org/x/term v0.19.0 => v0.26.0
go: upgraded golang.org/x/text v0.14.0 => v0.20.0
go: upgraded golang.org/x/tools v0.20.0 => v0.21.1-0.20240508182429-e35e4ccd0d2d
go: upgraded google.golang.org/genproto/googleapis/rpc v0.0.0-20240401170217-c3f982113cda => v0.0.0-20241118233622-e639e219e697
go: upgraded google.golang.org/grpc v1.62.1 => v1.63.2
go: upgraded google.golang.org/protobuf v1.33.0 => v1.35.2
```

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
LGTM

**Review by Defined2014 — APPROVED** [review]

**Review by wuhuizuo — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/run-integration-test

it is an old style job.

**Pull request merged**
