### PR TITLE
*: bump go to 1.16

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

try bump go to 1.16 so we can build this tools on mac m1 chip #437 

### What is changed and how it works?

update go mod to 1.1.6

### Check List 

Tests 

 - Unit test

Code changes

- None

Side effects

- None

Related changes

- None

### CODE REVIEW

**Comment by kennytm** [comment]
The `go.mod1` files are used to break the cyclic dependency between pingcap/tidb and this module. I don't think upgrading to Go 1.16 is going to allow us renaming it back to `go.mod`.

**Comment by Ehco1996** [comment]
> The `go.mod1` files are used to break the cyclic dependency between pingcap/tidb and this module. I don't think upgrading to Go 1.16 is going to allow us renaming it back to `go.mod`.

know it

**Pull request merged**
