### PR TITLE
pumpclient: remove dependency on the tidb repo

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

No circle dependency so that we can upgrade to module/v4

### What is changed and how it works?

TiDB already Init the log, so provide the `InitLogger` function is unnecessary.

### Check List 

Tests 

 - No code

Code changes

 - Has exported function/method change

Side effects

 - Breaking backward compatibility

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @WangXiangUSTC @lysu

**Review by lysu — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
if remove the initial log, the pump client can not print message in tidb's log, should we add it later?

**Comment by tiancaiamao** [comment]
We're not adopting module/v4, so this change is useless.

**Pull request closed without merging**
