### PR TITLE
diff: add config MaxIndexLength for tidb

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 

fix issue https://github.com/pingcap/tidb-tools/issues/399

### What is changed and how it works?
set MaxIndexLength to the max value.

### Check List 

Tests 

 - Manual test

### CODE REVIEW

**Comment by csuzhangxc** [comment]
TiDB also depends on this TiDB-Tools, does this change will affect the global variable used in TiDB itself? 😕 

But if we do not call these codes, it may have no side effects?

**Comment by WangXiangUSTC** [comment]
> TiDB also depends on this TiDB-Tools, does this change will affect the global variable used in TiDB itself? 😕

As long as the TiDB does not execute `setTiDBCfg` will not affect the TiDB's configuration

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
