### PR TITLE
sync-diff: add table match check

### LINKED ISSUE #583: sync-diff will not report error when upstream has table but downstream doesn't
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

upstream has all_mode.t2 and t1, downstream has all_mode.t2

2. What did you expect to see?

error: table all_mode.t1 does not exists in downstream

3. What did you see instead?

```
$ bin/sync_diff_inspector --config ~/Projects/ticdc/dm/tests/all_mode/conf/diff_config.toml
A total of 1 tables need to be compared

Comparing the table structure of ``all_mode`.`t2`` ... equivalent
Comparing the table data of ``all_mode`.`t2`` ... equivalent
_____________________________________________________________________________
Progress [============================================================>] 100% 0/Progress [============================================================>] 100% 0/0
A total of 1 table have been compared and all are equal.
You can view the comparision details through '/tmp/ticdc_dm_test/output/sync_diff.log'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 

close https://github.com/pingcap/tidb-tools/issues/583

add table match check. when met
1.  source exist tables but target not.
2. target exist tables but source not.
after we use table-filter as parameter.

### What is changed and how it works?
add a common check function in source.go

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Breaking backward compatibility

### CODE REVIEW

**Comment by lance6716** [comment]
need revert https://github.com/pingcap/ticdc/pull/3413 after this PR

**Review by lichunzhu — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by 3pointer** [comment]
/hold

wait for 5.3.1

**Review by Leavrth — APPROVED** [review]

**Pull request merged**
