### PR TITLE
checker: check primary/unique key exists

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
[dm#788](https://github.com/pingcap/dm/issues/788)

### What is changed and how it works?
check primary/unique key exist in table structure checker

Tests 
   - manually check with DM

### CODE REVIEW

**Comment by GMHDBJD** [comment]
@WangXiangUSTC @csuzhangxc PTAL

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
LGTM
🤔

**Review by WangXiangUSTC — APPROVED** [review]

**Comment by GMHDBJD** [comment]
@csuzhangxc @WangXiangUSTC Help me merge this pr.

**Pull request merged**
