### PR TITLE
checker: minor fix desc of MySQLServerIDChecker

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
Unfriendly error description
image

### What is changed and how it works?
change error description

### CODE REVIEW

**Comment by GMHDBJD** [comment]
@lance6716 PTAL

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Comment by lance6716** [comment]
what's the cause of this problem 😂

**Comment by kennytm** [comment]
probably to avoid the HTML tags

**Comment by GMHDBJD** [comment]
seems caused by [json.MarshalIndent](https://github.com/pingcap/dm/blob/master/checker/checker.go#L277)

**Pull request merged**
