### PR TITLE
sync-diff-inspector: support tls for sync-diff-inspector

### LINKED ISSUE #676: support tls for sync-diff-inspector
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #676 

### What is changed and how it works?
update config to support tls connection.

### Check List 

Tests 
 
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
maybe add some tests or manually test it

**Comment by Leavrth** [comment]
please take another look @lance6716

**Comment by lance6716** [comment]
lgtm

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
