### PR TITLE
checker: support ANSI_QUOTES

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
support ansi_quotes sql_mode in TablesChecker and ShardingTablesCheck

### What is changed and how it works?
add enableANSIQuotes and config the parser

Tests 

- manually test in DM

### CODE REVIEW

**Comment by GMHDBJD** [comment]
@WangXiangUSTC PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by GMHDBJD** [comment]
@csuzhangxc PTAL

**Comment by GMHDBJD** [comment]
cc @csuzhangxc

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
