### PR TITLE
test: fix integration tests timezone

### PR DESCRIPTION
**Pull request by glorv**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
why oringal PR's /run-all-tests passed 🤔

**Comment by lance6716** [comment]
or we should add `integration-test` as required?

**Comment by glorv** [comment]
> or we should add `integration-test` as required?

Seems the `integration-test` is not triggered in that PR since it's can only be triggered by explicit comment.

**Comment by lance6716** [comment]
CI failed

**Comment by lance6716** [comment]
and how about change integration-test to "Required" to early detect the failing @zhouqiang-cl

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
