### PR TITLE
.*: update tidb version

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 

https://github.com/pingcap/tidb-tools/blob/6ca94f01c59b038d6f88bd670a8d2bca4625f8fb/pkg/dbutil/table.go#L53
this line may cause panic, and is fixed in  https://github.com/pingcap/tidb/pull/14184

### What is changed and how it works?

update tidb's version

### CODE REVIEW

**Comment by kennytm** [comment]
I think it's time we remove that `replace github.com/google/pprof => github.com/lonng/pprof` line from go.mod.

**Comment by WangXiangUSTC** [comment]
@kennytm removed, PTAL again

**Review by kennytm — COMMENTED** [review]
Lgtm

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
