### PR TITLE
pump_client: remove log, print log to ioutil.Discard

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
tidb team don't want print log from pump client, so modify these code.
similar with sarama, if want to out put the log,  do like 
https://github.com/pingcap/tidb-binlog/blob/57b629f9b1071ffef50e25bcca5a1fa2e534e125/drainer/util.go#L45

### CODE REVIEW

**Comment by IANTHEREAL** [comment]
@coocood PTAL

**Comment by july2993** [comment]
currently, hard to tell if some code you use indirectly like in github.com/pingcap/tidb-tools/pkg/* will use log.Debug** or some day will, and the default level of `github.com/ngaut/log` is Debug

**Comment by WangXiangUSTC** [comment]
what is your suggestion? @july2993

**Comment by coocood** [comment]
Most of the log library have those methods:
```
Debugf
Infof
Warnf
Errorf
```
So if we define a logger interface that have those methods, whatever log lib TiDB use will be able to adapted to.

**Comment by holys** [comment]
You may like this: https://github.com/siddontang/loggers   @WangXiangUSTC

**Comment by coocood** [comment]
@holys 
Looks nice.
`Advanced` interface is what we need.

**Pull request closed without merging**
