### PR TITLE
feat(json): fix hidden column make by expression index

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #42294

### What is changed and how it works?
ignore hidden column generated by json column

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by sdojjy — APPROVED** [review]

**Comment by YangKeao** [comment]
@maxshuang It seems that you haven't signed the CLA? Will you agree the CLA?

**Comment by YangKeao** [comment]
As I've submitted another PR (https://github.com/pingcap/tidb-tools/pull/715) to fix this issue. I'll close this one. Thanks again for your contribution.

**Pull request closed without merging**
