### PR TITLE
sync_diff_inspector: optimize heap load for multi-sources

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve? 

It is not necessary to traverse all sources whenever it obtains one row.

### What is changed and how it works?

Just keep the heap saving one row for each source, otherwise the source has read to the end.
When the heap pops one row, it knows which source this row is from. So whenever the heap pops one row, push new one row from the source which the popped row is from.

### Check List 

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
the original code seems a lazy reading from each sources, could you explain what's the benifits of your changing?

**Comment by Leavrth** [comment]
> the original code seems a lazy reading from each sources, could you explain what's the benifits of your changing?

This function only returns one row each time, so I think it's better to record only the source which the last popped row is from. If we need a lazy reading, I think a variable `lastRowSource` is enough instead of array `sourceHaveData`.

**Review by 3pointer — APPROVED** [review]
LGTM, nice catch!

**Comment by Leavrth** [comment]
Due to sync_diff_inspector has been updated to version 2.0. This PR is outdated.

**Pull request closed without merging**
