### PR TITLE
upgrade pd-client to latest version

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

TiDB want to use latest pd but compile fail with:

```
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta-264-g8f0091ef1-dirty" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2020-03-02 10:05:41" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=8f0091ef1790eed8b23c961df97c64ce44b8fce0" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=master" ' -o bin/tidb-server tidb-server/main.go
# command-line-arguments
tidb-server/main.go:268:84: cannot use securityOption (type "github.com/pingcap/pd/v4/client".SecurityOption) as type "github.com/pingcap/pd/client".SecurityOption in argument to client.NewPumpsClient
tidb-server/main.go:270:93: cannot use securityOption (type "github.com/pingcap/pd/v4/client".SecurityOption) as type "github.com/pingcap/pd/client".SecurityOption in argument to client.NewLocalPumpsClient
make: *** [Makefile:210: server] Error 2
```

due to https://github.com/pingcap/pd/pull/2120 change pd client using new Semantic Import Versioning

### What is changed and how it works?

- go get -u github.com/pingcap/pd/v4@8ccbcd3
- rename import "github.com/pingcap/pd/client" => "github.com/pingcap/pd/v4/client"
- go mode tidy

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - go.mod
- import

Side effects

 - n/a

Related changes

 - n/a

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb-tools/320)

### CODE REVIEW

**Comment by lysu** [comment]
it seems go test still use old pd-client 

@shafreeck @nolouch PTAL, it seems it introduce many problem

**Comment by shafreeck** [comment]
What is `go.mod1` ?

**Comment by WangXiangUSTC** [comment]
> What is `go.mod1` ?

you can look https://github.com/pingcap/tidb-tools/pull/118 @shafreeck

**Comment by shafreeck** [comment]
> it seems go test still use old pd-client
> 
> @shafreeck @nolouch PTAL, it seems it introduce many problem

@lysu If the `go test` is still using `pd@v0`, the dependency would appear in `go.mod`, I do not see that in the file. 

BTW: We have many problems now because we did something wrong in the past.

**Comment by july2993** [comment]
> > it seems go test still use old pd-client
> > @shafreeck @nolouch PTAL, it seems it introduce many problem
> 
> @lysu If the `go test` is still using `pd@v0`, the dependency would appear in `go.mod`, I do not see that in the file.
> 
> BTW: We have many problems now because we did something wrong in the past.

I try update pd to v4 in tidb-binlog repo, but failed to start pump:
```
  1 [Thu Mar  5 16:53:49 CST 2020] <<<<<< RUNNING pump  >>>>>>
  2 panic: duplicate metrics collector registration attempted
  3
  4 goroutine 1 [running]:
  5 github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000140410, 0xc00024fac0, 0x1, 0x1)
  6     /Users/huangjiahao/go/pkg/mod/github.com/prometheus/client_golang@v1.0.0/prometheus/registry.go:399 +0xad
  7 github.com/prometheus/client_golang/prometheus.MustRegister(...)
  8     /Users/huangjiahao/go/pkg/mod/github.com/prometheus/client_golang@v1.0.0/prometheus/registry.go:176
  9 github.com/pingcap/pd/client.init.0()
 10     /Users/huangjiahao/go/pkg/mod/github.com/pingcap/pd@v1.1.0-beta.0.20190923032047-5c648dc365e0/client/metrics.go:83 +0x91
```
the `5c648dc365e0` version of pd is the version of  dependentcy of the tidb version in tidb-binlog
```
 21     github.com/pingcap/tidb v1.1.0-beta.0.20191119111543-77faf6466821                                                      │-rw-r--r--   1 huangjiahao  staff   134B Apr 23  2019 li.sh
```

I think the indirect dependency of pd is till using another version and it will not appear in `go.mod` but will appear in `go.sum`

**Comment by lysu** [comment]
@WangXiangUSTC  PTAL

**Review by july2993 — COMMENTED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]

**Pull request merged**
