### PR TITLE
*: remove checker

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

- remove checker tool

### What is changed and how it works?

- remove checker sources
- remove rule in Makefile
- remove introduce in READM

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@GregoryIan @amyangfei PTAL

**Comment by IANTHEREAL** [comment]
LGTM

**Comment by IANTHEREAL** [comment]
@amyangfei PTAL

**Review by amyangfei — COMMENTED** [review]
LGTM

**Pull request merged**
