### PR TITLE
syncer: fixed index already exist error

### PR DESCRIPTION
**Pull request by holys**
Although we have infoschema.ErrIndexExists,  sometimes it does return
tidb/mysql.ErrDupKeyName. If such error occurs, the program exits.

@GregoryIan  PTAL

### CODE REVIEW

**Comment by GregoryIan** [comment]
It can't be ignore easily

**Comment by GregoryIan** [comment]
Oh I made a mistake

**Comment by GregoryIan** [comment]
LGTM

**Comment by andelf** [comment]
LGTM

**Pull request merged**
