### PR TITLE
sync-diff: update tidb dependency

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #xxx

### What is changed and how it works?
Update tidb dependency, so need update tiflow, and tiflow repo use `20230823131104-05aa17143df8`. So let's use this version here, too

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by Leavrth** [comment]
blocked by https://github.com/pingcap/tidb-tools/pull/743

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
