### PR TITLE
*: update tidb and tiflow version

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #xxx

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
This is a duplicate of https://github.com/pingcap/tidb-tools/pull/814

Please also see https://github.com/pingcap/tidb-tools/issues/819

**Comment by Defined2014** [comment]
> This is a duplicate of #814
> 
> Please also see #819

I need the newest one TiDB version to support global index.

**Review by mjonss — APPROVED** [review]
LGTM

**Review by dveeden — APPROVED** [review]

**Pull request merged**
