### PR TITLE
update vendor for pd client

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
pd/pd-client changed to pd/client

### CODE REVIEW

**Comment by july2993** [comment]
LGTM

**Comment by gregwebs** [comment]
I am curious how parser.go got pulled in since it is a generated file.

**Comment by IANTHEREAL** [comment]
I think @WangXiangUSTC update vendor and them execute `git checkout ../parser.go`.

**Comment by IANTHEREAL** [comment]
LGTM

**Comment by WangXiangUSTC** [comment]
@gregwebs  I build parser.go in tidb, and move it to tools' vendor

**Pull request merged**
