### PR TITLE
tidb-binlog: Add RESOLVED as a new binlog type

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

There's no easy way to differenciate a message containing resolved
timestamp and one that is ordinary binlog.

By adding `RESOLVED` as a `BinlogType` and reuse the `commit_ts` field
for `resolved_ts`, the consumer can just decode all message as usual and
look out for `RESOLVED` binlogs.

### What is changed and how it works?

1. Add a third BinlogType: RESOLVED
2. Regenerate the go file.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by july2993** [comment]
just use your own branch to dev first

**Comment by suzaku** [comment]
> just use your own branch to dev first

👌

**Comment by IANTHEREAL** [comment]
LGTM

**Comment by IANTHEREAL** [comment]
@july2993 PTAL

**Comment by july2993** [comment]
lgtm

**Review by IANTHEREAL — APPROVED** [review]

**Comment by dveeden** [comment]
TiDB Binlog was moved to pingcap/tidb and is deprecated since v7.5.0 and removed in v8.4.0

**Comment by dveeden** [comment]
Filed #827 to cleanup binlog things a bit more.

**Pull request closed without merging**
