### PR TITLE
diff: fix block

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 

when killing the process of sync-diff-inspector, diff may firstly exit the `WriteSqls` goroutine, and then will be blocked if have fix SQLs to send to `sqlCh`.

### What is changed and how it works?

1. use select, add `case <-ctx.Done():`
2. remove the useless `wg.Add(1)` when have fix SQLs send to `sqlCh` by the way, because we can make sure the SQLs which send to `sqlCh` will be handled  before exit `WriteSqls` goroutine.  

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@csuzhangxc PTAL

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
LGTM

**Pull request merged**
