### PR TITLE
upgrade tidb module, remove deprecated auto random option

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Upgrade tidb related dependencies to the latest. Remove deprecated config `Experimental.AllowAutoRandom`. ref: https://github.com/pingcap/tidb/pull/16596

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to update the release branch. TiDB 4.0.3 has removed this option (https://github.com/pingcap/tidb/pull/18613) unfortunately tidb-tools 4.0.3 does not update.

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @WangXiangUSTC @leoppro  @kennytm

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by zier-one** [comment]
LGTM

**Review by zier-one — APPROVED** [review]

**Pull request merged**
