### PR TITLE
sync-diff: turn off new collation

### LINKED ISSUE #596: refine code
bypass some bot

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #596

### What is changed and how it works?

as title

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
need change DM integration CI after this PR merged

**Comment by lance6716** [comment]
blocked by https://github.com/pingcap/tidb/issues/32557

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
