### PR TITLE
Quote table name with back quote

### PR DESCRIPTION
**Pull request by felix021**

### CODE REVIEW

**Comment by felix021** [comment]
p.s. make checker安装依赖的时候遇到问题：
$ go get github.com/pingcap/tidb/parser
# github.com/pingcap/tidb/parser
../.go/src/github.com/pingcap/tidb/parser/lexer.go:92: undefined: yySymType
../.go/src/github.com/pingcap/tidb/parser/misc.go:500: undefined: yySymType
../.go/src/github.com/pingcap/tidb/parser/yy_parser.go:60: undefined: yySymType
../.go/src/github.com/pingcap/tidb/parser/yy_parser.go:61: undefined: yySymType
../.go/src/github.com/pingcap/tidb/parser/yy_parser.go:62: undefined: yySymType

**Comment by shenli** [comment]
@felix021 We use glide to resolve dependency. The parser package is already in vendor dir: https://github.com/pingcap/tidb-tools/tree/master/vendor/github.com/pingcap/tidb/parser

**Comment by shenli** [comment]
LGTM
@siddontang PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by shenli** [comment]
@felix021 Please sign the CLA.

**Comment by felix021** [comment]
CLA signed already.

**Comment by shenli** [comment]
@felix021 Thank you very much!

**Pull request merged**
