### PR TITLE
Cherry pick table filters to 3.1

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Cherry-pick #341, #347, #353 to tidb-pump-3.1.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @3pointer @YuJuncen

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by YuJuncen — APPROVED** [review]
LGTM

Am I a reviewer of this repository?

**Comment by kennytm** [comment]
Doesn't matter, you are a Reviewer in the SIG and the button is green 🙃

**Pull request merged**
