### PR TITLE
build: bring back the go mod and sum files

### LINKED ISSUE #661: can't import packet
When I import the package, the prompt is as follows.

➜  DBRTools git:(dev_sync_diff_inspect) ✗ go mod tidy
go: finding module for package github.com/pingcap/tidb-tools/sync_diff_inspector/config
go: finding module for package github.com/pingcap/tidb-tools/pkg/utils
go: found github.com/pingcap/tidb-tools/pkg/utils in github.com/pingcap/tidb-tools v6.1.0+incompatible
go: found github.com/pingcap/tidb-tools/sync_diff_inspector/config in github.com/pingcap/tidb-tools v6.1.0+incompatible

### PR DESCRIPTION
**Pull request by wuhuizuo**
The dep importing issue was existed in passed years, but currently it does not exist.

### What problem does this PR solve?

Issue Number: close #661 

### Check List 

Tests 

 - Manual test: 
    - `make build`
    - `make test`
 - No code

Code changes

 - None

Side effects

 - None

Related changes

 - None

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
tidb repo does not import tidb-tools now, so the old cycle import is solved

**Comment by wuhuizuo** [comment]
@3pointer @lance6716  Thanks! Could you finally approve it with comment `/merge`?

**Pull request merged**
