### PR TITLE
gomod: update tidb, parser to latest (#389)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 
Since release 3.0.18 has been checked out, we can update the master to use the rfc errors.

### What is changed and how it works?
Cherry-pick 98d05bb.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

N/A

Side effects

 - Breaking backward compatibility

Related changes

N/A

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
What about updating tidb/parser to latest master

**Review by amyangfei — COMMENTED** [review]
LGTM

**Comment by zier-one** [comment]
LGTM

**Review by zier-one — APPROVED** [review]

**Pull request merged**
