### PR TITLE
*: update vendor

### PR DESCRIPTION
**Pull request by tiancaiamao**
TiDB parser bug fix

https://github.com/pingcap/tidb/pull/2200

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
Why adding such many files for vendor update?

**Comment by tiancaiamao** [comment]
I don't know, I use the following command, any suggestion?

```
glide update
glide vc --use-lock-file
```

@qiuyesuifeng

**Comment by shenli** [comment]
@tiancaiamao You should ignore test files.

**Comment by shenli** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Pull request merged**
