### PR TITLE
update vendor for tidb

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
update to tidb v2.0.3

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@GregoryIan  @july2993  PTAL

**Review by july2993 — COMMENTED** [review]
LGTM

**Comment by IANTHEREAL** [comment]
u remove etcd, I update for #24

**Comment by WangXiangUSTC** [comment]
@GregoryIan  I don't remove etcd, I just modify  tidb's version in glide.yaml, and then `make update`.
how about update tidb in your pr, and I close this pr.

**Comment by IANTHEREAL** [comment]
ok

**Pull request closed without merging**
