### PR TITLE
sync_diff_inspector: use statically build

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #782

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by dveeden — APPROVED** [review]

**Review by dveeden — APPROVED** [review]

**Comment by wuhuizuo** [comment]
broken in buildings for mac targets.

**Comment by dveeden** [comment]
I assume this is the issue?
```
$ GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 make sync_diff_inspector 
GO111MODULE=on go build -ldflags '-X "github.com/pingcap/tidb-tools/pkg/utils.Version=v8.1.0-8-g2c9fecb" -X "github.com/pingcap/tidb-tools/pkg/utils.BuildTS=2024-06-12 05:56:32" -X "github.com/pingcap/tidb-tools/pkg/utils.GitHash=2c9fecb17c2f014b469bd1f0e36393dae1842773" -X "github.com/pingcap/tidb-tools/pkg/utils.GitBranch=master"' -o bin/sync_diff_inspector ./sync_diff_inspector
# github.com/cloudfoundry/gosigar
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:20:12: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:30:14: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:49:11: l.Get undefined (type LoadAverage has no field or method Get)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:55:11: m.Get undefined (type Mem has no field or method Get)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:61:11: m.GetIgnoringCGroups undefined (type Mem has no field or method GetIgnoringCGroups)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:67:11: s.Get undefined (type Swap has no field or method Get)
../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/sigar_shared.go:12:21: procTime.Get undefined (type *ProcTime has no field or method Get)
make: *** [Makefile:60: sync_diff_inspector] Error 1
```

**Comment by wuhuizuo** [comment]
> ../../../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.3.6/concrete_sigar.go:20:12: cpuUsage.Get undefined (type Cpu has no field or method Get)

Yes

**Comment by dveeden** [comment]
https://github.com/cloudfoundry/gosigar/blob/master/sigar_darwin.go heavily relies on C so that explains that.

**Pull request merged**
